name: build-macos-intel

on:
  workflow_dispatch:

env:
  REF_TAG: v1.1.1

jobs:
  build:

    runs-on: macos-12

    env:
      # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
      BUILD_TYPE: Release

    steps:
    - uses: actions/checkout@v4
      with:
        repository: ctlcltd/e2-sat-editor
        # ref: ${{ env.REF_TAG }}
        path: e2-sat-editor

    - name: Setup Homebrew
      run: brew install cmake ninja qt6 curl

    - name: Configure CMake
      working-directory: ${{github.workspace}}/e2-sat-editor/src
      run: |
        export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"
        cmake \
        -G Ninja \
        -B build \
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build
      working-directory: ${{github.workspace}}/e2-sat-editor/src
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    # - name: Test
    #   working-directory: ${{github.workspace}}/e2-sat-editor/src/build
    #   continue-on-error: true
    #   timeout-minutes: 1
    #   run: DEBUG=1 QT_QPA_PLATFORM=minimal ./e2\ SAT\ Editor.app/Contents/MacOS/e2\ SAT\ Editor

    - name: Deploy
      working-directory: ${{github.workspace}}/e2-sat-editor/src
      # continue-on-error: true
      run: |
        DESTDIR=../AppDir ninja -C build install
        cd AppDir/usr/local
        macdeployqt e2\ SAT\ Editor.app

    # - name: Test
    #   working-directory: ${{github.workspace}}/e2-sat-editor/src/AppDir
    #   continue-on-error: true
    #   timeout-minutes: 1
    #   run: DEBUG=1 QT_QPA_PLATFORM=minimal ./usr/local/e2\ SAT\ Editor.app/Contents/MacOS/e2\ SAT\ Editor

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{github.workspace}}/e2-sat-editor/src/AppDir
