name: test-crlf-win32

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: windows-2022

    env:
      BUILD_TYPE: Release

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v4
      with:
        repository: ctlcltd/e2-sat-editor
        path: e2-sat-editor

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32

    - name: Deploy
      working-directory: ${{github.workspace}}/e2-sat-editor/src
      continue-on-error: true
      shell: msys2 {0}
      run: |
        mkdir -p ../artifact
        #TODO convert LF to CRLF
        cat ../dist/common/Readme.txt.in | sed 's/$'"/`echo \\\r`/" > ../artifact/Readme.txt
        cat COPYING | sed 's/$'"/`echo \\\r`/" > ../artifact/License.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{github.workspace}}/e2-sat-editor/artifact
