name: test-port

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: macos-13

    steps:
    - name: Test MacPorts
      run: |
        echo $(which port)

    - name: Test 1
      run: |
        URL="https://github.com/macports/macports-base/releases/download/v2.10.2/MacPorts-2.10.2-13-Ventura.pkg"
        curl -L "$URL" -o ./MacPorts-2.10.2-13-Ventura.pkg
        installer -verbose -pkg MacPorts-2.10.2-13-Ventura.pkg -target /
        port -h
        port diagnose --quiet

    - name: Test 2
      run: |
        sudo port -N selfupdate

    - name: Test 3
      run: |
        sudo port -N install qt6-qtbase
