name: test-artifact

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: macos-14

    steps:
    - name: Download
      working-directory: ${{github.workspace}}
      continue-on-error: true
      run: |
        curl -L https://github.com/e2se/test-workflows/releases/download/v0.0.0-prerelease/1.7-artifact-macos-silicon.zip -o artifact.zip
        unzip -l artifact.zip
        unzip artifact.zip
        tar -xf artifact.tar
        ls -l artifact

    - name: Test
      working-directory: ${{github.workspace}}/artifact
      continue-on-error: true
      run: |
        ls -l e2\ SAT\ Editor.app/Contents/MacOS
        ./e2\ SAT\ Editor.app/Contents/MacOS/e2\ SAT\ Editor -style fusion --debug
        nohup ./e2\ SAT\ Editor.app/Contents/MacOS/e2\ SAT\ Editor -style fusion --debug &
        sleep 5
        killall e2\ SAT\ Editor
        cat nohup.out
