name: test-port

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: macos-15-intel

    steps:
    - name: Test MacPorts
      run: |
        echo $(which port)

    - name: Setup MacPorts
      uses: melusina-org/setup-macports@v1.1.5

    # - name: Test 1
    #   run: |
    #     port help
    #     sudo port diagnose --quiet

    - name: Test 2
      run: |
        sudo port -N selfupdate

    - name: Test 3
      run: |
        sudo port -N install qt6-qtbase
