name: test-artifact

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: macos-14

    steps:
    - name: Download
      working-directory: ${{github.workspace}}
      continue-on-error: true
      run: |
        curl -L https://github.com/e2se/test-workflows/releases/download/v0.0.0-pre/artifact.zip -o artifact.zip
        unzip -l artifact.zip
        unzip artifact.zip -d artifact
        ls -l artifact

    - name: Test
      working-directory: ${{github.workspace}}/artifact
      continue-on-error: true
      run: |
        ls -l e2\ SAT\ Editor.app/Contents/MacOS
        mkdir img
        # screencapture -C -T5 img/image.png &
        # ./e2\ SAT\ Editor.app/Contents/MacOS/e2\ SAT\ Editor --debug &
        # sleep 6
        # killall e2\ SAT\ Editor
        echo \#\!/bin/bash >> subcmd.sh
        echo "./e2\ SAT\ Editor.app/Contents/MacOS/e2\ SAT\ Editor --debug &" >> subcmd.sh
        echo "sleep 9" >> subcmd.sh
        echo "killall e2\ SAT\ Editor" >> subcmd.sh
        chmod +x subcmd.sh
        nohup bash subcmd.sh &        
        mv nohup.out img

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{github.workspace}}/artifact/img
