name: test-artifact

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: macos-14

    steps:
    - name: Download
      working-directory: ${{github.workspace}}
      continue-on-error: true
      run: |
        curl -L https://github.com/ctlcltd/e2-sat-editor/releases/download/v1.6.0/e2-sat-editor-1.6.0-unsigned-test-silicon-macos.zip -o artifact.zip
        unzip -l artifact.zip
        unzip artifact.zip -d artifact
        ls -l artifact

    - name: Test
      working-directory: ${{github.workspace}}/artifact
      continue-on-error: true
      run: |
        ls -l e2\ SAT\ Editor.app/Contents/MacOS
        ./e2\ SAT\ Editor.app/Contents/MacOS/e2\ SAT\ Editor -style fusion --debug
        nohup ./e2\ SAT\ Editor.app/Contents/MacOS/e2\ SAT\ Editor -style fusion --debug &
        sleep 5
        killall e2\ SAT\ Editor
        cat nohup.out
