name: test-artifact-win64

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-11-arm

    steps:
    - name: Download
      working-directory: ${{github.workspace}}
      continue-on-error: true
      run: |
        curl -L https://github.com/e2se/test-workflows/releases/download/v0.0.0-pre/artifact.zip -o artifact.zip
        unzip -l artifact.zip
        unzip artifact.zip -d artifact
        ls -l artifact

    - name: Test
      working-directory: ${{github.workspace}}/artifact
      continue-on-error: true
      run: |
        $w=New-Object -com WScript.Shell
        $u='[DllImport("user32.dll")] public static extern void keybd_event(byte b, byte s, uint f, int e);'
        Add-Type -MemberDefinition $u -Name Kbd -Namespace Win32
        md img
        start .\e2-sat-editor.exe --version
        sleep -s 2
        taskkill /F /im e2-sat-editor.exe
        sleep -s 2
        Start-Process -FilePath "e2-sat-editor.exe" -ArgumentList "--debug" -RedirectStandardOutput "img\logout.txt" -RedirectStandardError "img\logerr.txt"
        sleep -s 6
        $w.AppActivate("e2 SAT Editor")
        sleep -s 2
        [Win32.Kbd]::keybd_event(0x5b,0,0,0); [Win32.Kbd]::keybd_event(0x2c,0,0,0)
        sleep -s 1
        [Win32.Kbd]::keybd_event(0x5b,0,2,0); [Win32.Kbd]::keybd_event(0x2c,0,2,0)
        sleep -s 3
        taskkill /F /im e2-sat-editor.exe
        copy $HOME\Pictures\Screenshots\* img\

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{github.workspace}}/artifact/img
