name: test-artifact

on:
  workflow_dispatch:

jobs:
  test:

    runs-on: macos-14

    steps:
    - name: Test
      working-directory: ${{github.workspace}}
      continue-on-error: true
      run: |
        machine
